### ISSUE TITLE
Signed Integer Overflow - 67363984

### ISSUE THREAD

**Issue by Google-Autofuzz** [aquynh/capstone#1062]
Hello capstone team,

As part of our fuzzing efforts at Google, we have identified an issue affecting
capstone (tested with revision * master 93bfcf16c15daf3b26750fa2f7e2f65df1ac5738).

To reproduce, we are attaching a Dockerfile which compiles the project with
LLVM, taking advantage of the sanitizers that it offers. More information about
how to use the attached Dockerfile can be found here:
https://docs.docker.com/engine/reference/builder/

TL;DR instructions:
* `mkdir project`
* `cp Dockerfile /path/to/project`
* `docker build --no-cache /path/to/project`
* `docker run -it image_id_from_docker_build`

From another terminal, outside the container:
`docker cp /path/to/attached/reproducer running_container_hostname:/fuzzing/reproducer`
(reference: https://docs.docker.com/engine/reference/commandline/cp/)

And, back inside the container:
`/fuzzing/repro.sh /fuzzing/reproducer`

Alternatively, and depending on the bug, you could use gcc, valgrind or other
instrumentation tools to aid in the investigation. The sanitizer error that we
encountered is here:

Running: /tmp/poc
arch/SystemZ/SystemZInstPrinter.c:305:32: runtime error: negation of -2147483648 cannot be represented in type 'int32_t' (aka 'int'); cast to an unsigned type to negate this value to itself
SUMMARY: AddressSanitizer: undefined-behavior arch/SystemZ/SystemZInstPrinter.c:305:32 in 

We will gladly work with you so you can successfully confirm and reproduce this
issue. Do let us know if you have any feedback surrounding the documentation.

Once you have reproduced the issue, we'd appreciate to learn your expected
timeline for an update to be released. With any fix, please attribute the report
to "Google Autofuzz project".

We are also pleased to inform you that your project is eligible for inclusion to
the OSS-Fuzz project, which can provide additional continuous fuzzing, and
encourage you to investigate integration options.

Don't hesitate to let us know if you have any questions!

Google AutoFuzz Team
[artifacts_67363984.zip](https://github.com/aquynh/capstone/files/1560871/artifacts_67363984.zip)

**Comment by aquynh** [comment]
fixed, thanks!

**Comment by Google-Autofuzz** [comment]
Hi there,

We reviewed the change, and unfortunately the underlying issue still reproduces. Here's a link to some documentation that might be helpful to review for these types of bugs. Thanks so much for the effort!
