### ISSUE TITLE
x86: Cannot disassemble 'lock adc'

### ISSUE THREAD

**Issue by ceeac** [aquynh/capstone#1472]
The `adc` instruction is not recognized when used with a `lock` prefix:
```bash
$ cstool -d x32 "f0 13 45 08"
ERROR: invalid assembly code
```
(Should be `lock adc eax, [ebp + 8]`).
This happens both when using the `v4` branch or the `next` branch.

However, removing the lock prefix causes the instruction to be disassembled correctly:
```bash
$ cstool -d x32 "13 45 08"
 0  13 45 08                                         adc	eax, dword ptr [ebp + 8]
```

**Comment by aquynh** [comment]
fixed now in both "v4" & "next" branches, please confirm

**Comment by ceeac** [comment]
Does not work for me, both in `v4` and in `next`. Incidentally, I discovered more instructions that cannot be disassembled when used with lock prefixes, here is a list with all of these instructions:

- [ ] F0 03 45 08 -> `lock add eax,DWORD PTR [ebp+0x8]`
- [ ] F0 13 45 08 -> `lock adc eax,DWORD PTR [ebp+0x8]` (see above)
- [ ] F0 23 45 08 -> `lock and eax,DWORD PTR [ebp+0x8]`
- [ ] F0 0B 45 08 -> `lock or eax,DWORD PTR [ebp+0x8]`
- [ ] F0 2B 45 08 -> `lock sub eax,DWORD PTR [ebp+0x8]`

**Comment by aquynh** [comment]
fixed, will push soon.

btw, you may not cleanly build the new code. you can "make clean" & build again, to see the ADC issue fixed.

**Comment by ceeac** [comment]
Tried that already, and still does not work. The 8 bit `adc` with 0x12 opcode is recognized, but the 32 bit `adc` with 0x13 opcode is not recognized with the lock prefix.

**Comment by aquynh** [comment]
like below?

```
$ cstool x32 "f0124508 f0134508"
 0  f0 12 45 08          lock adc	al, byte ptr [ebp + 8]
 4  f0 13 45 08          lock adc	eax, dword ptr [ebp + 8]
```

i will push soon.

**Comment by ceeac** [comment]
yes

**Comment by aquynh** [comment]
fixed now for both "next" & "v4" branches.

**Comment by ceeac** [comment]
Can confirm it works now. Thanks!
