### ISSUE TITLE
CALL and JMP with rel16 argument must mask RIP with 0xffff

### ISSUE THREAD

**Issue by 10110111** [aquynh/capstone#456]
For relative jumps and calls with `rel16` argument, i.e. opcodees `E8` and `E9`, if `OperandSize==16`, the final RIP is masked with `0xffff`. Capstone doesn't do this.

Cases affected:
* 16 bit mode. Example: `0xfc16: E8 35 64` is disassembled as `call 0x1604e`, must be `call 0x604e`
* 32 & 64 bit modes. Example: `0x9123fc1b: 66 E8 35 64` is disassembled as `call 0x91236054`, must be `call 0x6054`

**Comment by aquynh** [comment]
is this true? note that Capstone converts all target addresses to absolute addresses.

**Comment by 10110111** [comment]
Yes, and it's the absolute addresses which appear wrong. Just see the Operation section of Intel's Instruction Set Reference for `JMP` and `CALL` instructions. There they explicitly write for e.g. near jumps:

    IF OperandSize = 16
        THEN (* OperandSize = 16 *)
            EIP<-tempEIP AND 0000FFFFH
        ELSE (* OperandSize = 64 *)
            RIP<-tempRIP;
    FI;

**Comment by aquynh** [comment]
fixed. please confirm, thanks.

**Comment by 10110111** [comment]
Not fixed for `0xfc26: E9 35 64` in 16 bit mode. It's `jmp 0x605e`, but disassembled as `jmp 0x1605e`.

**Comment by aquynh** [comment]
can you confirm now with the latest fix

**Comment by 10110111** [comment]
No, now `0xfff6: 66 E9 35 64 93 53` in 16-bit mode and `0x9123fff1: E9 35 64 93 53` in 32 bit mode as well as `0x649123fff1: E9 35 64 93 53` in 64 bit mode are broken. They shouldn't mask resulting RIP.

**Comment by aquynh** [comment]
just pushed a fix. can you check all your tests again now?

**Comment by 10110111** [comment]
The following still doesn't work:

* `0xffe1: 66 e8 35 64 93 53 call 0x5394641c` in 16 bit mode. Capstone loses carry from bit 15 to bit 16, reporting target address of `0x5393641c`.
* `0x649123ffe1: 66 e8 35 64 call 0x641a` in 64 bit mode. I'd expect immediate operand size to be 16 bit, but Capstone says 32 bit. (Note that is an unsupported instruction in 64 bit mode, according to Intel docs, but we still want some consistency in output, don't we?)
* `0x649123ffe1: 66 e9 35 64 jmp 0x641a` in 64 bit mode. Same as above
* `0xffe1: 66 e9 35 64 93 53 jmp 0x5394641c` in 16 bit mode. Capstone says `jmp 0x641c`.

**Comment by aquynh** [comment]
`0xfff6: 66 E9 35 64 93 53 in 16-bit mode`     <-- what is the expected output here?

**Comment by 10110111** [comment]
jmp 0x53946431

**Comment by aquynh** [comment]
`Not fixed for 0xfc26: E9 35 64 in 16 bit mode. It's jmp 0x605e, but disassembled as jmp 0x1605e.`

are you sure with the above? `E9 35 64` is **JMP rel32**, so the output should be ` jmp 0x1605e` because there is no need to mask `0xffff`.

**Comment by aquynh** [comment]
`0xffe1: 66 e8 35 64 93 53 call 0x5394641c in 16 bit mode. Capstone loses carry from bit 15 to bit 16, reporting target address of 0x5393641c.`

can you confirm the expected output of above code?

**Comment by 10110111** [comment]
It's 16-bit mode, and no `66` prefix is used. Thus `OperandSize==16`.

**Comment by aquynh** [comment]
so `0xffe1: 66 e8 35 64 93 53` = **call 0x641c**.

how about another the code above regarding "JMP rel32" ?

**Comment by 10110111** [comment]
> can you confirm the expected output of above code?

Yes, the expected output seems to be correct. What exactly makes you doubt?

**Comment by 10110111** [comment]
`0xffe1: 66 e8 35 64 93 53` in 16-bit mode has `66` prefix, thus operand size is 32 bits. Thus this is `jmp rel32` and follows rules for such jumps, i.e. no masking.
`E9 35 64` in 16 bit mode has no operand size override, thus operand size is 16 bits. Thus masking must be applied to target address.

**Comment by hlide** [comment]
@10110111 is right. That is, Prefix 0x66 switches between 16-bit and 32-bit to be opposite to the default operand size in CS segment/selector.

**Comment by hlide** [comment]
Same for 0x67 but to be opposite to the default address size in the segment/selector associated to the memory operand of the instruction. With no segment/selector prefix, it is *DS* by default or *SS* for implicit stack memory operands (*xSP*, *xBP*) or stack instructions.

**Comment by aquynh** [comment]
can you test the latest code in "master" branch?

to keep track of bugs being fixed, i added a new script `suite/regress.py`, so feel free to add any bugs you find in this file, then send a pull-request.

thanks

**Comment by 10110111** [comment]
The disassembly strings now seem OK, but why are these cases reported as having 32 bit operand?

    Intel64: 0x649123ffe1: 66 e8 35 64      call 0x641a
    Intel64: 0x649123ffe1: 66 e9 35 64      jmp  0x641a

It seems they should have 16 bit one.

**Comment by aquynh** [comment]
this issue with the size of immediate operands has been thoroughly fixed in the "next" branch. so if you really need this, please consider using the code from the "next" branch instead. (fyi, "next" branch code is quite stable)

will fix this in the "master" branch when i have more time.

**Comment by 10110111** [comment]
Just tried with the `next` branch, but the two cases mentioned above are still the same.

Also, should I even try to test `master` in the future? Or is it going to be dropped soon?

**Comment by aquynh** [comment]
fixed in the latest commit in the "next" branch.

the "next" branch will be released as v4.0 in the future, while "master" branch is for 3.x series. some less-important bugfixes will be ported back to "master" branch when i have more free time.

thanks.

**Comment by 10110111** [comment]
OK, seems to finally be fixed in `next`.
